== preplace

=== NAME
  preplace -  preplace [options]
  Version:  0.1 
  Location:  /home/micha//git/tools/preplace

 
=== DESCRIPTION
   preplace [options]
   Interactively replace all occurrences of param -f with param -t in files matched by -g.
   f is a regular expression.
   

=== ARGUMENTS

   Needed 
   -f "Regexpression" : What to replace
   -t "string" : Replace with string
   
   Optional 
   -a ask for every occurrence
   -g file globbing, e.g. -g "*.pl" 
      defaults to "*"
   -r recursion, recurse into subdirectories
   -h show this help
   -v show version and copyright information
   
   Copyright (c) 2006 Michael (misc) Myer, misc.myer@zoho.com
   

 
=== WEBSITE
   http://www.github.com/michael105

=== AUTHOR
   Michael (misc) Myer  misc.myer@zoho.com 

=== LICENSE
  
       This program is free software; you can redistribute it and/or modify
       it under the terms of the GNU General Public License as published by
       the Free Software Foundation; either version 2 of the License, or
       (at your option) any later version.
   
       This program is distributed in the hope that it will be useful,
       but WITHOUT ANY WARRANTY; without even the implied warranty of
       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
       GNU General Public License for more details.
   
       You should have received a copy of the GNU General Public License
       along with this program; if not, write to the Free Software
       Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
   
  

  

