
:hardbreaks:

link:README.adoc[Index]


== Misc::Tables 

=== NAME

*Misc::Tables* 

  Dump out a table
  Version: 0.1 
	
link:/perl/Misc/Tables.pm[/perl/Misc/Tables.pm]


=== DESCRIPTION

  Dump out a table


=== GLOBAL VARS
   
Borders
# Contains the chars of the borders, order: normal, none, compact
  
=== METHODS

add_row::
   


new::
   
Constructor

    - Arguments:

    -titles: Ref to an array with the colnames
-widths:	Ref to an array with the cols' width in chars
-maxwidths: Ref to an array containing the maximum colwidths in chars
-bordertype: 'normal', 'none', 'compact'  - defaults to normal
-align: 'left' (default), 'right'
-termwidth: optional, otherwise tries to determine the size automatic..


set_alignment::
   


set_bordertype::
   


set_maxwidths::
   


set_termwidth::
   


set_titles::
   


set_widths::
   


show::
   
Dumps out the table




=== WEBSITE

*http://www.github.com/michael105*

=== AUTHOR
  Michael (misc) Myer misc.myer@zoho.com

=== LICENSE

```
  
      This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

  

  
```



link:README.adoc[Index]
