

== Misc::MechanizeFunctions 

=== NAME
 Misc::MechanizeFunctions - Some  helper functions for WWW::Mechanize;
  Version: 0.1 
  Location: /home/micha/git/tools/perl/Misc/MechanizeFunctions.pm


=== DESCRIPTION
  Some  helper functions for WWW::Mechanize;


=== GLOBAL VARS
   
				sub {
						my ( $value, $type, $max_width, $width, $precision, $showmode ) = @_;
						$value;
				}
#		);

=== METHODS



=== WEBSITE
  http://www.github.com/michael105

=== AUTHOR
  Michael (misc) Myer misc.myer@zoho.com

=== LICENSE
  
      This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

  

  

